# English explanations for unit 12 (PA Licensing Law / RELRA), written to carry
# the same facts and the same emphasis as the Spanish originals.
EN = {
1: "RELRA (the Real Estate Licensing and Registration Act) is administered by the PENNSYLVANIA DEPARTMENT OF STATE through the STATE REAL ESTATE COMMISSION. The Commission has authority to issue, suspend, and revoke licenses, and to discipline licensees for violations of the law.",
2: "Under RELRA, a license is required when someone performs real estate activities FOR COMPENSATION on behalf of OTHERS. A licensed broker representing a buyer in exchange for a commission needs a license. The EXCEPTIONS include: owners selling their own property, attorneys acting under a power of attorney, people managing their own rental properties, and public officials performing their duties.",
3: "In Pennsylvania, a salesperson's license must be AFFILIATED with and held by a BROKER holding an active Pennsylvania license. The salesperson may NOT practice independently — every activity must be carried out under the broker's supervision. The broker is responsible for the actions of the salespeople affiliated with them.",
4: "To obtain a salesperson's license in Pennsylvania you must complete 75 HOURS of approved pre-licensure education, pass the licensing exam (which includes state and national portions), be at least 18 years old, and be of good moral character. No prior experience, personal interview with the Commission, or college degree is required.",
5: "In Pennsylvania, after passing the licensing exam the candidate has SIX MONTHS to apply for the license with the Commission. If they do not apply within that period, the exam results expire and the exam must be retaken. Do not let this deadline pass.",
6: "Pennsylvania real estate licenses renew every TWO YEARS (biennially). The license period is two years. To renew, licensees must complete the continuing education requirement (14 hours for both salespeople and brokers) and pay the applicable renewal fees. Failing to renew on time can leave the license lapsed.",
7: "Pennsylvania real estate salespeople (and brokers) must complete 14 HOURS of approved continuing education for each biennial renewal. Of those 14 hours, at least 3.5 must cover FAIR HOUSING and 3.5 must cover ETHICS. The remainder may be in other approved subjects.",
8: "The minimum age to apply for a Pennsylvania real estate salesperson license is 18 YEARS. That is the age of legal majority in Pennsylvania for entering binding contracts. A minor cannot obtain a license because they cannot legally sign representation agreements with clients.",
9: "The primary role of the Pennsylvania State Real Estate Commission is to LICENSE, REGULATE, and DISCIPLINE licensees in order to PROTECT THE PUBLIC. The Commission sets education standards, administers the licensing process, investigates complaints, and can impose discipline including fines, suspensions, and revocations.",
10: "A BROKER's license in Pennsylvania requires 240 HOURS of approved pre-licensure education. That is far more than the 75 hours required of salespeople, reflecting the greater responsibility and knowledge expected of a broker. Prior experience as a licensed salesperson is generally required as well.",
11: "To open a BRANCH OFFICE in Pennsylvania, the broker must obtain a BRANCH OFFICE LICENSE from the Commission and appoint a BRANCH MANAGER who holds an active broker's license. The branch cannot operate without that license. The branch manager is responsible for supervising the activities of every licensee working out of that office.",
12: "COMMINGLING — mixing client money (such as earnest money deposits) with the broker's personal or business funds — is a serious violation of RELRA. Client funds MUST be held in a separate escrow account. This protects clients' money if the broker runs into financial trouble.",
13: "The Commission has broad disciplinary authority: it can REVOKE or SUSPEND a license, impose PROBATION, issue FINES of up to $1,000 per violation, and/or require additional EDUCATION. Penalties are applied according to the severity of the violation. Criminal violations are handled separately through the criminal courts.",
14: "The Consumer Notice MUST be provided at the FIRST CONTACT with a consumer that involves a specific property. The document informs the consumer about the types of agency relationships available in Pennsylvania and the duties the licensee owes to different parties. It is mandatory and cannot be skipped — the licensee must obtain the consumer's acknowledgment of receipt.",
15: "The Consumer Notice must be delivered at the FIRST SUBSTANTIVE CONTACT with the consumer regarding a specific property — not later. If a buyer calls asking about a particular property, or a seller requests a listing consultation, that is the moment to present the Consumer Notice. This ensures consumers understand the agency relationship from the outset.",
16: "In Pennsylvania, to act as a DUAL AGENT (representing both buyer and seller in the same transaction), the licensee MUST obtain WRITTEN CONSENT FROM BOTH PARTIES. A dual agent owes reduced duties to both sides: they may not disclose one party's confidential information to the other, and cannot fully advocate for either.",
17: "In Pennsylvania, a DESIGNATED AGENT is a specific salesperson within a brokerage who is APPOINTED to represent ONLY ONE PARTY in a transaction. When the same firm represents both buyer and seller, the broker may designate one salesperson for the buyer and another for the seller, with the broker technically serving as dual agent. This allows fuller representation of each party.",
18: "When a salesperson is terminated by (or resigns from) a brokerage, the BROKER has 10 DAYS to notify the Pennsylvania State Real Estate Commission. During this transition the salesperson cannot conduct real estate activities until affiliating with a new broker. Reporting the change of affiliation promptly is the broker's responsibility.",
19: "The Pennsylvania State Real Estate Commission is made up of 11 MEMBERS appointed by the Governor: 6 licensed brokers, 2 licensed salespeople, and 3 members of the GENERAL PUBLIC (non-licensees). Including public members ensures consumer interests are represented in the regulation of the profession.",
20: "Under RELRA, paying referral fees or commissions to UNLICENSED people is ILLEGAL, regardless of the amount, any family relationship, or how little they participated in the transaction. Compensation for real estate activity in Pennsylvania may ONLY be paid to active licensees. Paying a non-licensee is a violation that can result in discipline for the licensee who makes the payment.",
}
