# English definitions, authored to match the Spanish source one-for-one.
EN_A = {
"abandonment":"Voluntary surrender of rights in a property without transferring them to anyone else.",
"abstract_of_title":"A condensed history of every recorded document and instrument affecting title to a specific property.",
"acceleration_clause":"A loan provision letting the lender declare the entire unpaid balance immediately due when the borrower defaults. It is distinct from a due-on-sale or alienation clause.",
"accretion":"The addition of land at the edge of a body of water through the natural deposit of sediment.",
"acknowledgment":"A formal declaration before a notary public certifying that a signature on a document is genuine and voluntary.",
"actual_notice":"Direct, personal knowledge of a fact, gained through one's own experience or direct communication.",
"ad_valorem_tax":"A tax based on the assessed value of property — the property tax.",
"adjustable_rate_mortgage_arm":"A mortgage loan whose interest rate changes periodically based on a financial index.",
"agency":"A fiduciary relationship in which one person (the agent) acts on behalf of and with the authority of another (the principal).",
"agent":"A person authorized to act on behalf of another (the principal) in dealings with third parties.",
"amortization":"The process of gradually reducing a loan balance through periodic payments of principal and interest.",
"appraisal":"A professional, impartial estimate of a property's market value as of a specific date.",
"assessed_value":"The value assigned to a property by the local taxing authority for calculating property taxes.",
"assignment":"The transfer of all remaining rights under a contract or lease from one party to another.",
"attachment":"A legal process placing a debtor's property under court custody as security for a debt.",
"balloon_payment":"A large final payment that pays off the balance of a loan that was not fully amortized.",
"bilateral_contract":"A contract in which both parties exchange promises — for example, sales contracts and listing agreements.",
"blockbusting":"The illegal practice of inducing owners to sell by suggesting that the arrival of members of a protected class will lower property values.",
"broker":"A senior real estate licensee authorized to operate their own firm, hire salespeople, and receive compensation for real estate services.",
"buyer_agency_agreement":"A written contract establishing the agency relationship between a buyer and a broker.",
"cap_rate_capitalization_rate":"The rate used to convert net operating income into an estimate of value; NOI divided by the property's value.",
"cash_flow":"The money left over after paying all operating expenses and mortgage payments on an investment property.",
"chain_of_title":"The chronological record of all previous owners of a property, from the original title to the present.",
"closing":"The final stage of a real estate transaction, where title transfers, funds change hands, and documents are signed.",
"closing_disclosure":"The TRID-required document itemizing all final loan and closing costs, delivered 3 business days before closing.",
"cloud_on_title":"A lien, claim, or encumbrance affecting a property's title that may prevent it from transferring freely.",
"commingling":"The illegal practice of mixing client funds with the licensee's personal or business funds.",
"commission":"The compensation a broker receives for real estate services, typically a percentage of the sale price.",
"community_property":"An ownership system in some states where assets acquired during marriage are owned equally by both spouses. It does not apply in PA.",
"comparables_comps":"Similar recently sold properties used in the sales comparison approach to estimate a property's value.",
"competent_parties":"People legally capable of entering contracts: of legal age, mentally competent, and not under undue influence.",
"condemnation":"The legal process by which government exercises eminent domain to take private property for public use, with just compensation.",
"condominium":"A form of ownership in which the owner individually owns their unit and shares co-ownership of the building's common areas.",
"consideration":"Something of value — money, a promise, goods — given in exchange for something else; an essential element of a valid contract.",
"constructive_notice":"Knowledge the law presumes everyone has because the information is publicly available in official records.",
"contingency":"A condition in a contract that must be satisfied for the contract to become binding — for example, financing or inspection contingencies.",
"contract_for_deed":"An installment sale agreement in which the seller keeps legal title until the final payment; also called an installment land contract.",
"conventional_loan":"A mortgage loan that is neither insured nor guaranteed by any government agency.",
"cooperative_co_op":"A form of ownership where residents own shares in a corporation that owns the building, rather than owning individual units.",
"deed":"The written legal document that transfers title from one person (grantor) to another (grantee). The deed is the instrument of transfer; it is not a synonym for the legal concept of title.",
"deed_in_lieu_of_foreclosure":"A voluntary transfer of title from borrower to lender to avoid the foreclosure process.",
"deed_of_trust":"A mortgage document conveying title to a trustee as security for a loan; used in many states in place of a traditional mortgage.",
"default":"Failure to meet the obligations of a contract, especially failure to make loan payments.",
"depreciation":"Loss of property value from any cause: physical deterioration, functional obsolescence, or economic obsolescence. Also: a tax deduction for wear and tear.",
"designated_agent":"In Pennsylvania, a specific salesperson within a firm appointed to represent one party exclusively in a transaction.",
"dual_agency":"A relationship where one agent or firm represents both buyer and seller in the same transaction, requiring written consent from both parties.",
"due_on_sale_clause":"A mortgage provision requiring the loan to be paid in full if the property is sold or transferred.",
"easement":"The right of one person to use another's property for a specific purpose — for example, a right of way or utility lines.",
"eminent_domain":"The government's power to take private property for public use while paying the owner just compensation.",
"encroachment":"An unauthorized intrusion of an improvement or structure onto another person's property.",
"encumbrance":"Any claim, lien, charge, or restriction on a property that affects its value or use.",
"equity":"The difference between a property's market value and the outstanding balance of the liens against it.",
"escrow":"An arrangement in which a neutral third party holds funds or documents until the conditions of a transaction are met.",
"executed_contract":"A contract that has been fully performed by all parties.",
"executory_contract":"A contract in which obligations remain to be performed by one or more parties.",
"fair_housing_act":"The federal law prohibiting discrimination in the sale, rental, and financing of housing based on race, color, religion, national origin, sex, familial status, and disability.",
"familial_status":"A protected class under the Fair Housing Act covering families with children under 18, pregnant women, and people in the process of adopting.",
"fee_simple":"The most complete form of real property ownership; the owner holds unlimited rights of use, disposition, and inheritance.",
"fha_loan":"A mortgage loan insured by the Federal Housing Administration, allowing lower down payments and more flexible qualification.",
"fiduciary":"A person with a legal duty to act in another's best interest, with loyalty, confidentiality, and care.",
"fixture":"An item that was originally personal property but became real property by being permanently attached to the land or building.",
"foreclosure":"The legal process by which a lender takes possession of and sells a property when the borrower defaults on loan payments.",
"general_lien":"A lien affecting all of a debtor's property, both real and personal — for example, a court judgment.",
"general_warranty_deed":"A deed in which the seller warrants title against all claims, including those arising under previous owners.",
"grm_gross_rent_multiplier":"A factor used to estimate a rental property's value: sale price divided by gross monthly rent.",
}
