EN_B = {
"ground_lease":"A long-term lease of land only, where the tenant builds and owns the improvements.",
"highest_and_best_use":"The most profitable, legally permissible, physically possible, financially feasible, and maximally productive use of a property.",
"homestead_exemption":"A reduction in assessed value for property tax purposes, available to owners who use the property as their principal residence.",
"index_lease":"A lease where rent increases are tied to a published economic index, such as the CPI.",
"intestate":"Dying without a valid will; property passes to heirs under the state's laws of descent.",
"joint_tenancy":"A form of co-ownership with right of survivorship; when one co-owner dies, their share passes automatically to the survivors.",
"landlord":"An owner who rents property to a tenant; also called the lessor.",
"lease":"A contract transferring the right to use and occupy a property for a period of time in exchange for rent.",
"leasehold_estate":"The tenant's interest in a property during the lease term; a temporary possessory right.",
"lessee":"The person who rents a property and pays rent; also called the tenant.",
"lessor":"The owner who grants the lease; also called the landlord.",
"leverage":"Using borrowed money to control a higher-value asset, magnifying both gains and losses.",
"lien":"A legal claim against a property as security for a debt; it can affect the transfer of title.",
"listing_agreement":"A bilateral contract between an owner and a broker authorizing the broker to market the property in exchange for compensation.",
"loan_to_value_ratio_ltv":"The percentage of a property's value that is financed by the loan (loan amount ÷ appraised value).",
"market_value":"The most probable price a property would bring in a normal market between an informed buyer and an informed seller.",
"mechanic_s_lien":"A lien filed against a property by contractors, subcontractors, or suppliers who were not paid for work or materials.",
"mill_rate":"A unit for measuring property tax; 1 mill = $1 per $1,000 of assessed value (0.001, or 0.1%).",
"mortgage":"The instrument creating a lien on property as security for a loan; the borrower keeps title.",
"mortgagee":"The lender in a mortgage transaction, who receives the lien on the property as security.",
"mortgagor":"The borrower in a mortgage transaction, who grants the lien on their property as security for the loan.",
"net_lease":"A lease where the tenant pays base rent plus some or all of the property's operating expenses.",
"net_operating_income_noi":"Gross income minus vacancy losses and operating expenses, calculated before debt service.",
"option_contract":"A unilateral contract giving the buyer the right, but not the obligation, to purchase a property at a set price within a set period.",
"pennsylvania_human_relations_act_phra":"The state law prohibiting discrimination in housing, employment, and public accommodations, covering classes beyond the federal ones: age and ancestry.",
"percentage_lease":"A lease where the tenant pays a minimum base rent plus a percentage of gross sales above a threshold.",
"personal_property":"Movable property not affixed to the land (chattel); everything that is not real estate.",
"points":"Prepaid interest on a loan; 1 point = 1% of the loan amount. Paid to obtain a lower interest rate.",
"power_of_attorney":"A legal document authorizing one person (the attorney-in-fact) to act for another in legal or financial matters.",
"principal":"In an agency relationship, the person who authorizes the agent to act on their behalf.",
"private_mortgage_insurance_pmi":"Insurance required on conventional loans with a down payment under 20%; it protects the lender, not the borrower.",
"proration":"The proportional division of expenses — taxes, rents — between buyer and seller based on the closing date.",
"real_estate":"The land and everything permanently attached to it: buildings, structures, and improvements.",
"real_property":"The land, the improvements permanently attached to it, and the bundle of legal rights that comes with ownership.",
"reconciliation":"The final step of the appraisal process, where the appraiser weighs the results of the three approaches to value to reach a final estimate.",
"redlining":"The illegal practice of denying loans or insurance in certain geographic areas based on their racial or ethnic composition.",
"relra":"Real Estate Licensing and Registration Act: the Pennsylvania law governing the licensing and conduct of real estate professionals.",
"respa":"Real Estate Settlement Procedures Act: the federal law requiring disclosure of closing costs and prohibiting kickbacks among service providers.",
"riparian_rights":"The rights of an owner whose land adjoins a river or stream to use that water.",
"salesperson":"An entry-level real estate licensee who must work under the supervision of an actively licensed broker.",
"secondary_mortgage_market":"The market where existing mortgage loans are bought and sold among investors and institutions (Fannie Mae, Freddie Mac).",
"special_assessment":"An additional tax levied on owners whose property benefits from specific public improvements — new sidewalks or sewers, for example.",
"specific_lien":"A lien affecting only one particular property — a mortgage, property tax lien, or mechanic's lien.",
"statute_of_frauds":"The law requiring certain contracts, including real estate contracts, to be in writing to be enforceable.",
"steering":"The illegal practice of directing buyers or renters toward or away from certain neighborhoods based on protected characteristics.",
"sublease":"A transfer of part of the original tenant's leasehold rights to a third party; the original tenant remains liable to the landlord.",
"tenancy_at_sufferance":"Possession of a property after the lease has expired, without the landlord's consent; also called holdover tenancy.",
"tenancy_at_will":"A tenancy with no fixed term that either party may end with proper notice.",
"tenancy_by_the_entirety":"A form of co-ownership available only to married spouses, with right of survivorship; neither spouse can sell without the other's consent.",
"tenancy_in_common":"A form of co-ownership where each owner holds a share that can be sold or inherited independently; there is no right of survivorship.",
"tenant":"A person who occupies another's property under a lease, paying rent.",
"tila_truth_in_lending_act":"The federal law requiring lenders to disclose the Annual Percentage Rate (APR) and other loan terms to borrowers.",
"title":"Evidence of ownership rights in real estate; the bundle of rights to possess, use, and dispose of it.",
"title_insurance":"Insurance protecting the owner and/or lender against title defects that existed before closing but were not found in the title search.",
"title_search":"An examination of public records to confirm the seller holds legal title and to uncover undisclosed liens or defects.",
"township":"In Pennsylvania, a unit of municipal government. Not to be confused with a survey township, the theoretical 6-mile square used in the federal rectangular survey system.",
"transaction_licensee":"In Pennsylvania, a licensee who facilitates a transaction by performing ministerial acts without representing either party.",
"unilateral_contract":"A contract in which only one party makes a promise; the other party performs but does not promise — an option contract or open listing, for example.",
"va_loan":"A mortgage loan guaranteed by the Department of Veterans Affairs, available to eligible veterans, active military, and surviving spouses; no down payment required.",
"void_contract":"A contract with no legal effect from the outset because it lacks an essential element or involves an illegal purpose.",
"voidable_contract":"A valid contract that one party may rescind under certain circumstances — for example, one signed by a minor.",
"warranty_deed":"A deed in which the seller warrants title against all claims, either under all previous owners (general) or only during their own ownership (special).",
"wetlands":"Areas where water covers the soil or is present near the surface; regulated by the Army Corps of Engineers and the EPA under the Clean Water Act.",
"zoning":"Government regulation dividing land use into categories — residential, commercial, industrial — to control development.",
}
