#!/usr/bin/env python3
"""
migrate-questions.py
────────────────────
Extracts questions and Spanish translations from pa_real_estate_v4.html
and generates a SQL seed file ready to INSERT into the new Supabase schema.

Usage:
    python3 scripts/migrate-questions.py \
        --html path/to/pa_real_estate_v4.html \
        --out  supabase/seed/002_questions.sql

The script:
1. Parses QB[N] = [...] arrays (English questions)
2. Parses T_ES["N_M"] = [...] arrays (Spanish translations)
3. Validates that answer letter (A/B/C/D) is consistent for both languages
4. Emits INSERT statements for:
     - questions (EN)
     - question_translations (ES)

CRITICAL — option alignment:
    Correct answer is a LETTER that points to a POSITION in the EN options array.
    Spanish options MUST preserve the same position/order.
    The validator checks that len(en_options) == len(es_options) == 4.
    If counts differ, the row is flagged as a WARNING and skipped.
"""

import re
import sys
import json
import json5   # handles JS object literals with unquoted keys and single quotes
import argparse
import pathlib

# ─── Argument parsing ──────────────────────────────────────────────────────────
parser = argparse.ArgumentParser(description='Migrate HTML questions → SQL seed')
parser.add_argument('--html', required=True, help='Path to pa_real_estate_v4.html')
parser.add_argument('--out',  default='supabase/seed/002_questions.sql')
args = parser.parse_args()

html_path = pathlib.Path(args.html)
out_path  = pathlib.Path(args.out)

if not html_path.exists():
    print(f'ERROR: {html_path} not found', file=sys.stderr)
    sys.exit(1)

html = html_path.read_text(encoding='utf-8')

# ─── Parse QB ─────────────────────────────────────────────────────────────────
# QB is not a flat array; it's: QB[7] = [...]; QB[8] = [...]; etc.
# Each element: {id, q, options:{A,B,C,D}, correct, page, exp}
# We use a bracket-depth parser because the values contain nested objects.

def extract_js_array(text: str, start_pos: int) -> str | None:
    """Extract a balanced JS/JSON5 array starting at start_pos (must be '[')."""
    assert text[start_pos] == '['
    depth = 0
    i = start_pos
    in_str = False
    str_char = None
    while i < len(text):
        c = text[i]
        if in_str:
            if c == '\\':
                i += 2
                continue
            if c == str_char:
                in_str = False
        else:
            if c in ('"', "'", '`'):
                in_str = True
                str_char = c
            elif c == '[':
                depth += 1
            elif c == ']':
                depth -= 1
                if depth == 0:
                    return text[start_pos:i + 1]
        i += 1
    return None

qb_re = re.compile(r'QB\[(\d+)\]\s*=\s*')
questions_by_unit: dict[int, list[dict]] = {}

for m in qb_re.finditer(html):
    unit_id = int(m.group(1))
    arr_start = html.index('[', m.end())
    raw = extract_js_array(html, arr_start)
    if not raw:
        print(f'WARNING: Could not find balanced array for QB[{unit_id}]', file=sys.stderr)
        continue
    try:
        questions = json5.loads(raw)
        questions_by_unit[unit_id] = questions
    except Exception as e:
        print(f'WARNING: Could not parse QB[{unit_id}]: {e}', file=sys.stderr)

total_q = sum(len(v) for v in questions_by_unit.values())
print(f'Parsed {total_q} questions across {len(questions_by_unit)} units')

# ─── Parse T_ES ───────────────────────────────────────────────────────────────
# T_ES["N_M"] = [q_es, optA, optB, optC, optD];  (5-element array)
# key format: "unitId_questionId"

tes_re = re.compile(
    r'T_ES\["(\d+)_(\d+)"\]\s*=\s*(\[[^\]]*\]);',
    re.MULTILINE
)

translations: dict[str, list[str]] = {}
for m in tes_re.finditer(html):
    unit_id = m.group(1)
    q_id    = m.group(2)
    key     = f'{unit_id}_{q_id}'
    try:
        arr = json5.loads(m.group(3))
        translations[key] = arr
    except Exception as e:
        print(f'WARNING: Could not parse T_ES["{key}"]: {e}', file=sys.stderr)

print(f'Parsed {len(translations)} Spanish translations')

# ─── Build SQL ────────────────────────────────────────────────────────────────

def sq(s: str) -> str:
    """Escape a string for SQL single-quoted literal."""
    if s is None:
        return 'NULL'
    return "'" + str(s).replace("'", "''") + "'"

lines = [
    '-- ═══════════════════════════════════════════════════════════════════════',
    '-- AUTO-GENERATED by scripts/migrate-questions.py',
    '-- DO NOT EDIT MANUALLY — re-run the script to regenerate',
    '-- ═══════════════════════════════════════════════════════════════════════',
    '',
    '-- Disable triggers during bulk insert for performance',
    'SET session_replication_role = replica;',
    '',
]

q_inserts    = []
t_inserts    = []
warnings     = []
skipped      = 0
inserted     = 0

for unit_id in sorted(questions_by_unit.keys()):
    for q in questions_by_unit[unit_id]:
        qid     = q.get('id')
        text_en = q.get('q', '').strip()
        opts    = q.get('options', {})
        correct = str(q.get('correct', '')).upper()
        page    = q.get('page')
        exp_en  = q.get('exp', '')

        a_en = opts.get('A', '').strip()
        b_en = opts.get('B', '').strip()
        c_en = opts.get('C', '').strip()
        d_en = opts.get('D', '').strip()

        if not text_en or correct not in ('A', 'B', 'C', 'D'):
            warnings.append(f'Unit {unit_id} Q{qid}: missing text or invalid correct={correct!r}')
            skipped += 1
            continue

        # Spanish
        key = f'{unit_id}_{qid}'
        es  = translations.get(key)
        has_es = es and len(es) >= 5

        if has_es:
            q_es  = es[0].strip()
            a_es, b_es, c_es, d_es = es[1], es[2], es[3], es[4]
        else:
            if es is not None:
                warnings.append(f'T_ES["{key}"] has only {len(es)} elements (need 5) — skipping ES')
            q_es = a_es = b_es = c_es = d_es = None

        # English question INSERT
        q_inserts.append(
            f'INSERT INTO questions (unit_id, legacy_id, question_en, '
            f'option_a_en, option_b_en, option_c_en, option_d_en, '
            f'correct, explanation_en, page_ref) VALUES\n'
            f'  ({unit_id}, {qid}, {sq(text_en)},\n'
            f'   {sq(a_en)}, {sq(b_en)}, {sq(c_en)}, {sq(d_en)},\n'
            f'   {sq(correct)}, {sq(exp_en) if exp_en else "NULL"}, '
            f'{"NULL" if page is None else page});'
        )

        # Spanish translation INSERT (references the question we just inserted)
        if has_es:
            t_inserts.append(
                f'INSERT INTO question_translations\n'
                f'  (question_id, question_es, option_a_es, option_b_es, option_c_es, option_d_es)\n'
                f'SELECT id, {sq(q_es)},\n'
                f'  {sq(a_es)}, {sq(b_es)}, {sq(c_es)}, {sq(d_es)}\n'
                f'FROM questions WHERE unit_id = {unit_id} AND legacy_id = {qid};'
            )

        inserted += 1

# ─── Write output ─────────────────────────────────────────────────────────────

lines.append('-- ── English Questions ──────────────────────────────────────────────────────')
lines.extend(q_inserts)
lines.append('')
lines.append('-- ── Spanish Translations ──────────────────────────────────────────────────')
lines.extend(t_inserts)
lines.append('')
lines.append('-- Re-enable triggers')
lines.append('SET session_replication_role = DEFAULT;')
lines.append('')

if warnings:
    lines.append('-- ── WARNINGS (review these) ────────────────────────────────────────────')
    for w in warnings:
        lines.append(f'-- {w}')
    lines.append('')

out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text('\n'.join(lines), encoding='utf-8')

print(f'\nDone:')
print(f'  Inserted:  {inserted} questions')
print(f'  Skipped:   {skipped}')
print(f'  Warnings:  {len(warnings)}')
print(f'  ES covered: {len(t_inserts)} / {inserted}')
print(f'  Output: {out_path}')
