#!/usr/bin/env python3
"""
migrate-glossary.py — Extract GLOSSARY from pa_real_estate_v4.html → SQL seed.
Usage: python3 scripts/migrate-glossary.py --html path/to/file.html --out supabase/seed/003_glossary.sql
"""
import re, sys, json5, argparse, pathlib

parser = argparse.ArgumentParser()
parser.add_argument('--html', required=True)
parser.add_argument('--out', default='supabase/seed/003_glossary.sql')
args = parser.parse_args()

html = pathlib.Path(args.html).read_text(encoding='utf-8')

# GLOSSARY = [ {slug, term, def, units?}, ... ]
m = re.search(r'(?:const\s+)?GLOSSARY\s*=\s*(\[)', html)
if not m:
    print('ERROR: GLOSSARY not found', file=sys.stderr); sys.exit(1)

def extract_js_array(text, start_pos):
    depth=0; i=start_pos; in_str=False; str_char=None
    while i < len(text):
        c = text[i]
        if in_str:
            if c=='\\': i+=2; continue
            if c==str_char: in_str=False
        else:
            if c in ('"',"'",'`'): in_str=True; str_char=c
            elif c=='[': depth+=1
            elif c==']':
                depth-=1
                if depth==0: return text[start_pos:i+1]
        i+=1
    return None

raw = extract_js_array(html, m.start(1))
glossary = json5.loads(raw)
print(f'Parsed {len(glossary)} glossary entries')

def sq(s):
    if s is None: return 'NULL'
    return "'" + str(s).replace("'","''") + "'"

lines = [
    '-- AUTO-GENERATED by scripts/migrate-glossary.py',
    'SET session_replication_role = replica;', '',
]

for g in glossary:
    slug    = g.get('slug') or g.get('id', '')
    term    = g.get('term') or g.get('t', '')
    defn    = g.get('def') or g.get('d', '')
    unit_ids= g.get('units') or g.get('u') or []
    if not slug or not term: continue
    unit_arr = '{' + ','.join(str(u) for u in unit_ids) + '}' if unit_ids else 'NULL'
    lines.append(
        f"INSERT INTO glossary_terms (slug, term_en, definition_en, unit_ids) VALUES\n"
        f"  ({sq(slug)}, {sq(term)}, {sq(defn)}, "
        f"{'NULL' if not unit_ids else sq(unit_arr)});"
    )

lines += ['', 'SET session_replication_role = DEFAULT;', '']

out = pathlib.Path(args.out)
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('\n'.join(lines), encoding='utf-8')
print(f'Written {len(glossary)} entries → {out}')
